# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-19 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 9, 36, 15, 918661)),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 9, 36, 15, 923828)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 9, 36, 15, 919898)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 9, 36, 15, 917689)),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 9, 36, 15, 922699)),
        ),
    ]
